SocInfo/Models/Team.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SocInfo.Models
{
    public class Team
    {
        public int id { get; set; }
        public string name { get; set; }
        public string shortName { get; set; }
        public string squadMarketValue { get; set; }
        public string crestUrl { get; set; }
    }

    public class Player
    {
        public int id { get; set; }
        public string name { get; set; }
        public string position { get; set; }
        public int jerseyNumber { get; set; }
        public string dateOfBirth { get; set; }
        public string nationality { get; set; }
        public string contractUntil { get; set; }
        public string marketValue { get; set; }
    }
}

SocInfo/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocInfo.Models;
using RestSharp;
using Newtonsoft.Json.Linq;

namespace SocInfo.Controllers
{
    public class TeamController : Controller
    {
        // GET: Team
        public ActionResult Index(string team)
        {
            team = (team == "") ? "Newcastle United FC" : team;

            ViewBag.TeamName = team;

            Team teamModel = GetTeamInfo(team);

            ViewBag.TeamId = teamModel.id;

            List <Player> playerModel = GetTeamPlayers(teamModel.id);
            List<Fixture> fixtureModel = GetTeamFixtures(teamModel.id);
            
            return View(Tuple.Create(playerModel, fixtureModel, teamModel));

        }

        // GET: Team Info
        public Team GetTeamInfo(string team)
        {
            TeamsController teamController = new TeamsController();
            Team currentTeam = new Team();

            foreach (Team curTeam in teamController.TeamsRequest())
            {
                if (team == curTeam.name)
                {
                    currentTeam = curTeam;
                }
            }

            return currentTeam;
        }

        // Player Info
        public List<Player> GetTeamPlayers(int teamId)
        {
            // Create list of players
            List<Player> teamPlayers = new List<Player>();

            // Retrieve positions from API
            RestClient client = new RestClient("http://api.football-data.org");

            // Create request
            RestRequest request = new RestRequest("/v1/teams/" + teamId + "/players", Method.GET);
            request.AddHeader("X-Auth-Token", "dd3e9cffe47c403e8b485b7a536874e0");
            request.AddHeader("X-Response-Control", "minified");

            // Retrieve response
            JObject returnedPlayers = JObject.Parse(client.Execute(request).Content);

            // Add each player  to list
            foreach (JToken playerToken in returnedPlayers["players"])
            {
                teamPlayers.Add(ParsePlayer(playerToken));
            }

            return teamPlayers;
        }

        // ParsePlayer method
        // --------------------
        static Player ParsePlayer(JToken player)
        {
            // Add Fixture details
            Player newPlayer = new Player();
            newPlayer.id = (int)player["id"];
            newPlayer.name = (string)player["name"];
            newPlayer.position = (string)player["position"];
            newPlayer.jerseyNumber = (int?)player["jerseyNumber"] ?? 0;
            newPlayer.dateOfBirth = (string)player["dateOfBirth"];
            newPlayer.nationality = (string)player["nationality"];
            newPlayer.contractUntil = (string)player["contractUntil"];
            newPlayer.marketValue = (string)player["marketValue"];

            // Add player
            return newPlayer;
        }

        // Fixture Info
        public List<Fixture> GetTeamFixtures(int teamId)
        {
            // Create list of players
            List<Fixture> teamFixtures = new List<Fixture>();

            // Retrieve positions from API
            RestClient client = new RestClient("http://api.football-data.org");

            // Create request
            RestRequest request = new RestRequest("/v1/teams/" + teamId + "/fixtures", Method.GET);
            request.AddHeader("X-Auth-Token", "dd3e9cffe47c403e8b485b7a536874e0");
            request.AddHeader("X-Response-Control", "minified");

            // Retrieve response
            JObject returnedFixtures = JObject.Parse(client.Execute(request).Content);

            // Add each fixture to list
            foreach (JToken playerToken in returnedFixtures["fixtures"])
            {
                teamFixtures.Add(FixturesController.ParseFixture(playerToken));
            }

            return teamFixtures.OrderByDescending(d => d.matchday).ToList();
        }
    }
}

SocInfo/Controllers/TeamsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using SocInfo.Models;
using Newtonsoft.Json.Linq;
using RestSharp;
using System.Linq;

namespace SocInfo.Controllers
{
    public class TeamsController : Controller
    {
        // GET: Teams
        public ActionResult Index()
        {
            return View(TeamsRequest());
        }

        // TeamsRequest method
        // -------------------
        // Retrieves a json object containing teams
        // and then parses each team and adds to a list
        // of teams which is returned
        public List<Team> TeamsRequest()
        {
            // Declare list of teams
            List<Team> teams = new List<Team>();

            // Retrieve teams from
            RestClient client = new RestClient("http://api.football-data.org");

            // Create request
            RestRequest request = new RestRequest("/v1/soccerseasons/426/teams", Method.GET);
            request.AddHeader("X-Auth-Token", "dd3e9cffe47c403e8b485b7a536874e0");
            request.AddHeader("X-Response-Control", "minified");

            // Retrieve response
            JObject returnedTeams = JObject.Parse(client.Execute(request).Content);

            // Add each fixture to fixture list
            foreach (JToken teamToken in returnedTeams["teams"])
            {
                teams.Add(ParseTeam(teamToken));
            }

            return teams.OrderBy(o => o.name).ToList();
        }

        // ParseTeam method
        // --------------------
        // It accepts a json token (with a single team contained)
        // and casts it to a custom Team object and then returns that
        // object.
        public Team ParseTeam(JToken team)
        {
            // Add Team
            Team newTeam = new Team();
            newTeam.id = (int)team["id"];
            newTeam.name = (string)team["name"];
            newTeam.shortName = (string)team["shortName"];
            newTeam.squadMarketValue = (string)team["squadMarketValue"];
            newTeam.crestUrl = (string)team["crestUrl"];

            // Add fixture
            return newTeam;
        }

        // GetTeamInfo method
        // --------------------
        // It accepts a team name and the required piece of information
        // and returns the result
        public string GetTeamInfo(string teamName, string info)
        {
            string result = "";
            
            foreach (Team team in TeamsRequest())
            {
                if (team.name == teamName)
                {
                    result = team.crestUrl;
                }
            }

            return result;
        }
    }
}

SocInfo/Views/Team/Index.cshtml
@model Tuple<List<SocInfo.Models.Player>, List<SocInfo.Models.Fixture>, SocInfo.Models.Team>
@{
    ViewBag.Title = ViewBag.TeamName;
}

<br />
<br />
<br />

<h2>@ViewBag.TeamName</h2>

<br />

<div class="row">
    
    <div class="col-md-2">
        <br/>
        
        <img src="@Model.Item3.crestUrl" alt="@Model.Item3.name logo" height="150" width="150" />
    </div>

    <div class="col-md-10">
        <h3>@ViewBag.TeamName Players</h3>

        <table class="table">
            <tr>
                <th>
                    Player
                </th>
                <th>
                    Nation
                </th>
                <th>
                    Position
                </th>
                <th>
                    Number
                </th>
                <th>
                    Value
                </th>
            </tr>

            @foreach (var player in Model.Item1.Take(5))
            {
                <tr>
                    <td>
                        @player.name
                    </td>
                    <td>
                        @player.nationality
                    </td>
                    <td>
                        @player.position
                    </td>
                    <td>  
                        @player.jerseyNumber
                    </td>
                    <td> 
                        @player.marketValue
                    </td>
                </tr>
            }
        </table>
        <p><a class="btn btn-default" href="">View all &raquo;</a></p>
    </div>
    
</div>

<div class="row">

    <div class="col-md-12">
        <h3>@ViewBag.TeamName Fixtures</h3>

        <table class="table">
            <tr>
                <th>Date</th>
                <th>Matchday</th>
                <th></th>
                <th>Home Team</th>
                <th></th>
                <th></th>
                <th></th>
                <th>Away Team</th>
                <th></th>
            </tr>

            @foreach (var teamFixture in Model.Item2.Take(10))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => teamFixture.date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => teamFixture.matchday)
                    </td>
                    <td>
                        <!-- logo -->
                        <img src="@Html.Action("GetTeamInfo", "Teams", new { teamName = teamFixture.homeTeamName, info = "" })" alt="" height="40" width="40" />
                    </td>
                    <td>
                        @Html.ActionLink(teamFixture.homeTeamName, "../Team/Index", new { team = teamFixture.homeTeamName })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => teamFixture.homeTeamGoals)
                    </td>
                    <td>v</td>
                    <td>
                        @Html.DisplayFor(modelItem => teamFixture.awayTeamGoals)
                    </td>
                    <td>
                        @Html.ActionLink(teamFixture.awayTeamName, "../Team/Index", new { team = teamFixture.awayTeamName })
                    </td>
                    <td>
                        <!-- logo -->
                        <img src="@Html.Action("GetTeamInfo", "Teams", new { teamName = teamFixture.awayTeamName, info = "" })" alt="" height="40" width="40" />
                    </td>
                </tr>
            }

        </table>

        <p><a class="btn btn-default" href="">View all &raquo;</a></p>

    </div>



</div>